### ISSUE TITLE
Windows binary

### ISSUE THREAD

**Issue by sergeevabc** [mrom1/minilockcpp#1]
Dear @mrom1,
Could you be so kind to generate ```.exe``` for the rest of us who are mere Windows users w/o compiler?

**Comment by mrom1** [comment]
Hi @sergeevabc 
thanks for showing interest in this somewhat old repository. I will add a Windows release soon and update the external dependencies to make it easier for windows users to compile this library

**Comment by mrom1** [comment]
Windows release added. It was more effort than I thought it would be, at this moment the windows release is restricted to an older blake2 version. This should not be a problem because it doesn't affect security nor performance for the minilock use case.

I will add a CLI in the future to not be dependent on the GUI. See issue #2 

Issue closed.
